<div class="col-md-12">


<div id="tabs" class="col-md-8 col-md-offset-2">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Ente consumidor de harina de trigo</a>
    </li>
    <li role="presentation"><a href="#profile"  aria-controls="profile" role="tab" data-toggle="tab">Datos de dueño</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Datos de encargado</a></li>
     <li role="presentation"><a href="#requerido" aria-controls="requerido" role="tab" data-toggle="tab">materia prima requerida</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Maquinarias</a></li>
     <li role="presentation"><a href="#capacidad" aria-controls="capacidad" role="tab" data-toggle="tab">capacidad</a></li>

  </ul>

  <!-- Tab panes -->
  		 	
 
  	
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
  		<form id="form_emp" method="post" action="">	
		<div class="form-group">
		<label for="">Codigo SICA <font id="requerido_aste">*</font></label>
		<input type="text" class="form-control" id="codigo" name="codigo" >
		</div>

		<div class="form-group">
		<label for="">Tipo de RIF <font id="requerido_aste">*</font></label>
		<select name="figura" id="figura" class="form-control" > 
		<option value="">--seleccione--</option>
		<option value="V">V</option>
		<option value="J">J</option>
		</select> 
		</div>

		<div class="form-group">
		<label for="">RIF <font id="requerido_aste">*</font></label>
		<input type="text" class="form-control" id="rif" name="rif" >
		</div>

		<div class="form-group">
		<label for="">Nombre o razon social <font id="requerido_aste">*</font></label>
		<input type="text" class="form-control" id="razon" name="razon" >
		</div>


		<div class="form-group">
		<label for="">Estado <font id="requerido_aste">*</font></label>
		<select name="estados" id="estados" class="form-control">
		<option value="">--seleccione--</option>
		<?php for ($i=0; $i < count($this->panadero->estados) ; $i++):?>
		<option value="<?php echo $this->panadero->estados[$i]['id_estado'] ?>" <?php echo $valor = ($this->panadero->estados[$i]['estado']=="Sucre") ? 'selected' : '' ; ?>><?php echo $this->panadero->estados[$i]['estado'] ?></option>
		<?php endfor; ?>
		</select>
		</div>


		<div class="form-group">
		<label for="">Municipio <font id="requerido_aste">*</font></label>
		<select name="municipio" id="municipio" class="form-control">
		<option value="">--seleccione--</option>
		<?php for ($i=0; $i < count($this->panadero->municipios) ; $i++):?>
		<option value="<?php echo $this->panadero->municipios[$i]['id_municipio'] ?>" <?php echo $valor = ($this->panadero->municipios[$i]['municipio']=="Sucre") ? 'selected' : '' ; ?>><?php echo $this->panadero->municipios[$i]['municipio'] ?></option>
		<?php endfor; ?>
		</select>
		</div>


		
		<div class="form-group">
		<label for="">Parroquia <font id="requerido_aste">*</font></label>
		<select name="parroquia" id="parroquia" class="form-control">
		<option value="">--seleccione--</option>
		<?php for ($i=0; $i < count($this->panadero->parroquia) ; $i++):?>
		<option value="<?php echo $this->panadero->parroquia[$i]['id_parroquia'] ?>" ><?php echo $this->panadero->parroquia[$i]['parroquia'] ?></option>
		<?php endfor; ?>
		</select>
		</div>

		

		<div class="form-group">
		<label for="">tipo de ente <font id="requerido_aste">*</font></label>
		<select name="tipo_ente" id="tipo_ente" class="form-control" > 
		<option value="">--seleccione--</option>
		<option value="42-Panadería y Pasteleria">42-Panadería y Pasteleria</option>
		<option value="75-Panaderías Comunales CLAP">75-Panaderías Comunales CLAP</option>
		<option value="109-Pastelería">109-Pastelería</option>
		<option value="56-Panadería Venezuela">56-Panadería Venezuela</option>
		</select> 
		</div>

		<div class="form-group">
		<label for="">circuito <font id="requerido_aste">*</font></label>
		<select name="circuito" id="circuito" class="form-control" > 
		<option value="">--seleccione--</option>
		<option value="c1">circuito 1</option>
		<option value="c2">circuito 2</option>
		<option value="c3">circuito 3</option>
		</select> 
		</div>

		<div class="form-group">
		<label for="">Telefono </label>
		<input type="text" class="form-control" id="emp_tlf" name="emp_tlf[]" >
		 <div class="div_agregar_tlf_emp">
		 	 <span class="glyphicon glyphicon-plus" id="agregar_tlf_emp" aria-hidden="true"></span>
		 </div>
		 <div id="show_tlf_emp">
			
		</div>

		

		</div>

		<div class="form-group">
		<label for="">Correo electronico</label>
		<input type="text" class="form-control" id="emp_email" name="emp_email[]" >
		<div class="div_agregar_email_emp">
		 	 <span class="glyphicon glyphicon-plus" id="agregar_email_emp" aria-hidden="true"></span>
		 </div>
		 <div id="show_email_emp">
			
		</div>
		</div>			
		</form>
    </div>
    <div role="tabpanel" class="tab-pane" id="profile">

		
		<form id="form_due" method="post" action="">	
		<div class="form-group">
		<label for="">Nacionalidad</label>
		<select name="nacionalidad" id="nacionalidad" class="form-control" > 
		<option value="">--seleccione--</option>
		<option value="V">V</option>
		<option value="J">J</option>
		</select> 
		</div>
		
		<div class="form-group">
		<label for="">cedula</label>
		<input type="text" class="form-control" id="cedula" name="cedula" >
		</div>

		<div class="form-group">
		<label for="">nombres</label>
		<input type="text" class="form-control" id="nombres" name="nombres" >
		</div>

		<div class="form-group">
		<label for="">apellidos</label>
		<input type="text" class="form-control" id="apellidos" name="apellidos" >
		</div>

		<div class="form-group">
		<label for="">sexo</label>
		<select name="sexo" id="sexo" class="form-control">
		<option value="">--seleccione--</option>
		<option value="M">M</option>
		<option value="F">F</option>
		</select>
		</div>


		<div class="form-group">
		<label for="">Telefono</label>
		<input type="text" class="form-control" id="due_tlf" name="due_tlf[]" >
		 <div class="div_agregar_tlf_due">
		 	 <span class="glyphicon glyphicon-plus" id="agregar_tlf_due" aria-hidden="true"></span>
		 </div>
		 <div id="show_tlf_due">
			
		</div>
		</div>
		

		<div class="form-group">
		<label for="">Correo electronico</label>
		<input type="text" class="form-control" name="due_email" id="due_email" >
		<div class="div_agregar_email_due">
		 	 <span class="glyphicon glyphicon-plus" id="agregar_email_due" aria-hidden="true"></span>
		 </div>
		  <div id="show_email_due">
			
		</div>
		</div>

	

		</form>



    </div>
    <div role="tabpanel" class="tab-pane" id="messages">


    	
		<div class="form-group">
		<label for="">Nacionalidad</label>
		<select name="enc_nacionalidad" id="enc_nacionalidad" class="form-control" > 
		<option value="">--seleccione--</option>
		<option value="V">V</option>
		<option value="J">J</option>
		</select> 
		</div>
		
		<div class="form-group">
		<label for="">cedula</label>
		<input type="text" class="form-control" id="enc_cedula" name="enc_cedula" >
		</div>

		<div class="form-group">
		<label for="">nombres</label>
		<input type="text" class="form-control" id="enc_nombres" name="enc_nombres" >
		</div>

		<div class="form-group">
		<label for="">apellidos</label>
		<input type="text" class="form-control" id="enc_apellidos" name="enc_apellidos" >
		</div>

		<div class="form-group">
		<label for="">sexo</label>
		<select name="enc_sexo" id="enc_sexo" class="form-control">
		<option value="">--seleccione--</option>
		<option value="M">M</option>
		<option value="F">F</option>
		</select>
		</div>


		<div class="form-group">
		<label for="">Telefono</label>
		<input type="text" class="form-control" id="enc_tlf" name="enc_tlf[]" >
		<div class="div_agregar_tlf_enc">
		 	 <span class="glyphicon glyphicon-plus" id="agregar_tlf_enc" aria-hidden="true"></span>
		 </div>
		 <div id="show_tlf_enc">
			
		</div>
		</div>

		<div class="form-group">
		<label for="">Correo electronico</label>
		<input type="text" class="form-control" id="enc_email" name="enc_email[]" >
		<div class="div_agregar_email_enc">
		 	 <span class="glyphicon glyphicon-plus" id="agregar_email_enc" aria-hidden="true"></span>
		 </div>
		  <div id="show_email_enc">
			
		</div>
		</div>
    </div>
    <div role="tabpanel" class="tab-pane" id="requerido">
    	
		<div class="form-group">
		<label for="">harina</label>
		<input type="text" class="form-control" id="harina" name="harina" >
		</div>

		<div class="form-group">
		<label for="">azucar</label>
		<input type="text" class="form-control" id="azucar" name="azucar" >
		</div>

		<div class="form-group">
		<label for="">sal</label>
		<input type="text" class="form-control" id="sal" name="sal" >
		</div>

		<div class="form-group">
		<label for="">manteca</label>
		<input type="text" class="form-control" id="manteca" name="manteca" >
		</div>

		<div class="form-group">
		<label for="">margarina</label>
		<input type="text" class="form-control" id="margarina" name="margarina" >
		</div>

		<div class="form-group">
		<label for="">levadura</label>
		<input type="text" class="form-control" id="levadura" name="levadura" >
		</div>

		<div class="form-group">
		<label for="">aceite</label>
		<input type="text" class="form-control" id="aceite" name="aceite" >
		</div>
    </div>
    <div role="tabpanel" class="tab-pane" id="settings">
    	

	
		<div class="form-group">
		<label for="">maquina</label>
		<select class="form-control" id="maquina" name="maquina[]" >
			<option value="cocina">Cocina</option>
			<option value="congelador">Congelador</option>
			<option value="batidor">Batidor</option>
			<option value="nevera">Nevera</option>
			<option value="horno">Horno</option>
			<option value="amasadora">Amasadora</option>
			<option value="mezcladora">Mezcladora</option>
			<option value="laminador">Lamanidor</option>
			<option value="bandeja">Bandeja</option>
			<option value="carro de bandeja">Carro de bandeja</option>
			<option value="cuarto frio">cuarto frio</option>
			<option value="mesa panadero">mesa panadero</option>
		</select>
		</div>

		<div class="form-group">
		<label for="">cantidad</label>
		<input type="text" class="form-control" id="cantidad" name="cantidad[]" >
		</div>

		<div class="form-group">
		<label for="">estatus</label>
		<select class="form-control" id="estatus" name="estatus[]">
			<option value="posee">Posee</option>
			<option value="requerido">Requerido</option>
		</select>
		</div>
		<button type="button" id="agregar_maquina" class="form-control">agregar</button>
		<div id="area_maquina_show">
		<table class="table table-hover">';
		<tr id="despues">
			<td>maquina</td>
			<td>cantidad</td>
			<td>estatus</td>
		</tr>
		</table>
		</div>
		<div id="area_maquina_input">
			
		</div>



    </div>
     <div role="tabpanel" class="tab-pane" id="capacidad">
     		
     	
		
		<div class="form-group">
		<label for="">Capacidad operativa</label>
		<input type="text" class="form-control" id="cap_operativa" name="cap_operativa" >
		</div>

		<div class="form-group">
		<label for="">Capacidad de almacen</label>
		<input type="text" class="form-control" id="cap_almacen" name="cap_almacen">
		</div>

		<div class="form-group">
		<label for="">Capacidad instalada</label>
		<input type="text" class="form-control" id="cap_instalada" name="cap_instalada" >
		</div>
     </div>
  </div>

<button type="button" id="prueba1">prueba1</button>



</div>



 
</div>
			

		
		

