<div class="col-md-12">

<div class="isquierdo-foto-panaderos col-md-5">
	<img class="img-responsive" src=" <?php echo BASE_URL."public/img/portada.jpg" ?> " alt="">
</div>
<div class="derecho-lista col-md-7">
	
	<div id="accordion">
	  <h3>Registro de consumidores de trigo inscritos en el SICA del estado Sucre</h3>
		  <div>
		    <p>Registro de consumidores de trigo inscritos en el SICA del estado Sucre. <br>
			un registro integrado para el censo de los trabajadores del procesamiento de la harina de trigo, que tiene como finalidad normalizar la data del censo actual y cruzarla con la data de EPS comercializadora de alimentos<br><br>
		
			<a href="<?php echo BASE_URL ?>ingresar">Registrar cosumidor de harina de trigo.</a> 

		     </p>
		  </div>
	  <h3>Busqueda por codigo SICA</h3>
		  <div>
		    	
		    	<div class="col-md-6 col-md-offset-3">
			<div class="form-group">
			<label for="">Codigo SICA</label>
			<input type="text" class="form-control" id="codigo" name="codigo" >
			</div></div>
			<div id="lista1" class="col-md-12">
	


			</div>
			


		  </div>
	  <h3>Busqueda por RIF</h3>
		  <div>
		    	
		    	<div class="col-md-6 col-md-offset-3">
			<div class="form-group">
			<label for="">tipo de rif</label>
			<select class="form-control" id="tipo_rif" name="tipo_rif" >
			<option value=""></option>
			<option value="V">V</option>
			<option value="J">J</option>
			</select>
			</div>
			<div class="form-group">
			<label for="">rif</label>
			<input type="text" class="form-control" id="rif" name="rif" >
			</div>
			<button type="button" id="btn_buscar_por_rif"  class="btn btn-default">Buscar</button>
			</div>
			<div id="lista2" class="col-md-12">
	


			</div>


		  </div>
	  <h3>Cruse de bases de datos</h3>
		  <div>
		    	
		    <div class="col-md-10 col-md-offset-1">
			cruze de bases de datos generales.
			<br><br><br><br>
			
			
			
			<ul>
				<li>
					<a href="<?php BASE_URL ?>pdf/cruze2">cruze general con productos en ultima factura</a>
				</li>
				<li>
					<a href="<?php BASE_URL ?>pdf/cruzar">cruze general por RIF</a>
				</li>
			</ul>		
			


		  </div> </div>
	  <h3>¿que es SICA?</h3>
		  <div>
		    <p>Redactar un brebe resumen de sus objetivos</p>
		  
		  </div>
	  <h3>Estadisticas</h3>
		  <div>
		    <p>En construccion </p>
		  </div>
	</div>
</div>







</div>
			

		

