<div class="col-md-12">

<div class="isquierdo-foto-panaderos col-md-6">
	<img class="img-responsive" src=" <?php echo BASE_URL."public/img/portada.jpg" ?> " alt="">
</div>
<div class="derecho-lista col-md-6">
	
	<div id="accordion">
	  <h3>Registro de consumidores de trigo inscritos en el SICA del estado Sucre</h3>
	  <div>
	    <p>Registro de consumidores de trigo inscritos en el SICA del estado Sucre. <br>
		un registro integrado para el censo de los trabajadores del procesamiento de la harina de trigo, qie tiene como finalidad normalizar la data del censo altual y cruzarla con la data de EPS comercializadora de alimentos S.A <br><br>
	
		<a href="<?php echo BASE_URL ?>ingresar">Registrar cosumidor de harina de trigo.</a> 

	     </p>
	  </div>
	  <h3>gestios de registros</h3>
	  <div>
	    <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In suscipit faucibus urna. </p>
	  </div>
	  <h3>¿que es SICA?</h3>
	  <div>
	    <p> 

Redactar un brebe resumen de sus objetivos
</p>
	  
	  </div>
	  <h3>Estadisticas</h3>
	  <div>
	    <p>En construccion </p>
	  </div>
	</div>

</div>





</div>
			

		
		

